# Generated by Django 3.0.4 on 2020-03-22 13:52

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='produto_id',
            field=models.CharField(max_length=200, validators=[core.validators.check_product_existence]),
        ),
    ]
