# Generated by Django 3.0.4 on 2020-03-16 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200316_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorito',
            old_name='id_produto',
            new_name='produto_id',
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('cliente', 'produto_id')},
        ),
    ]
