# Generated by Django 3.0.4 on 2020-03-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200322_1605'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorito',
            name='cliente_produto',
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('cliente', 'produto_id')},
        ),
    ]
