# Generated by Django 3.0.4 on 2020-03-20 00:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_favorito_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='hash',
            field=models.CharField(default=core.models._create_hash, max_length=200, unique=True),
        ),
    ]
