# Generated by Django 3.0.4 on 2020-03-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200322_1627'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Customer',
        ),
    ]
