# Generated by Django 3.0.4 on 2020-03-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200322_1639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorito',
            new_name='Favorite',
        ),
    ]
