# Generated by Django 3.0.4 on 2020-03-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200322_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='cliente',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='produto_id',
            new_name='product_id',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('customer', 'product_id')},
        ),
    ]
